- hosts: "{{ variable_host | default('localhost') }}"
  tasks:
    - name: Generated Self Signed certificates
      shell: docker exec -it nginx-proxy bash -c 'openssl req  -subj "/C=JO/CN=*.metastudio.org"  -x509 -nodes -days 365  -newkey rsa:2048 -keyout /etc/nginx/certs/metastudio.org.key -out /etc/nginx/certs/metastudio.org.crt'
