- hosts: "{{ variable_host | default('localhost') }}"
  tasks:
    - name: Nginx Reverse Proxy to server DNS
      docker_container:
        name: nginx-proxy
        image: jwilder/nginx-proxy
        networks:
          - name: doer-network
            ipv4_address: 172.20.0.10
        ports:
          - "80:80"
          - "443:443"
        state: started
        tty: true
        detach: true
        volumes:
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
